# Generated by Django 5.2 on 2026-04-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_svadba', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['name'], 'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
        migrations.RemoveField(
            model_name='drink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='massage',
        ),
        migrations.AddField(
            model_name='drink',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='drink',
            name='is_alcoholic',
            field=models.BooleanField(default=False, verbose_name='Алкогольный'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название напитка'),
        ),
        migrations.AlterModelTable(
            name='drink',
            table='drinks',
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('UN', 'Не знаю'), ('YES', 'Приду'), ('NO', 'Не приду')], default='UN', max_length=3, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('preferred_drinks', models.ManyToManyField(blank=True, to='main_svadba.drink', verbose_name='Предпочитаемые напитки')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'db_table': 'guests',
                'ordering': ['-created_at'],
            },
        ),
    ]
