# Generated by Django 5.2 on 2026-05-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_svadba', '0002_alter_drink_options_remove_drink_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('will_come', models.BooleanField()),
                ('alcohol', models.JSONField(default=list)),
                ('alcohol_comment', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='preferred_drinks',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
