# Generated by Django 5.2 on 2026-05-17 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_svadba', '0003_guestresponse_remove_guest_preferred_drinks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
